config/routes.rb
Rails.application.routes.draw do
  # get 'welcome/index', to: 'welcome#index'

  resources :channels
  resources :districts
  resources :cities
  resources :provinces
  resources :welcome

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/channel.rb
class Channel < ApplicationRecord
  belongs_to :district

  attr_accessor :district_name
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :set_channel, only: [:show, :edit, :update, :destroy]

  # GET /channels
  # GET /channels.json
  def index
    @channels = Channel.all

  end

  # GET /channels/1
  # GET /channels/1.json
  def show

  end

  # GET /channels/new
  def new
    @channel = Channel.new
  end

  # GET /channels/1/edit
  def edit
  end

  # POST /channels
  # POST /channels.json
  def create
    @channel = Channel.new(channel_params)

    respond_to do |format|
      if @channel.save
        format.html { redirect_to @channel, notice: 'Channel was successfully created.' }
        format.json { render :show, status: :created, location: @channel }
      else
        format.html { render :new }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /channels/1
  # PATCH/PUT /channels/1.json
  def update
    respond_to do |format|
      if @channel.update(channel_params)
        format.html { redirect_to @channel, notice: 'Channel was successfully updated.' }
        format.json { render :show, status: :ok, location: @channel }
      else
        format.html { render :edit }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /channels/1
  # DELETE /channels/1.json
  def destroy
    @channel.destroy
    respond_to do |format|
      format.html { redirect_to channels_url, notice: 'Channel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_channel
      @channel = Channel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def channel_params
      params.require(:channel).permit(:company, :address, :district_id, :long, :lat, :status)
    end
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/views/channels/_form.html.erb
<%= form_with(model: channel, local: true) do |form| %>
  <% if channel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(channel.errors.count, "error") %> prohibited this channel from being saved:</h2>

      <ul>
      <% channel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :company %>
    <%= form.text_field :company, id: :channel_company %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :channel_address %>
  </div>

  <div class="field">
    <%= form.label :district_id %>
    <%= form.collection_select(:district_id, District.all, :id, :name) %>
  </div>

  <div class="field">
    <%= form.label :long %>
    <%= form.text_field :long, id: :channel_long %>
  </div>

  <div class="field">
    <%= form.label :lat %>
    <%= form.text_field :lat, id: :channel_lat %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status, id: :channel_status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/channels/edit.html.erb
<h1>Editing Channel</h1>

<%= render 'form', channel: @channel %>

<%= link_to 'Show', @channel %> |
<%= link_to 'Back', channels_path %>

app/views/channels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Channels</h1>

<table class="table">
  <thead>
    <tr>
      <th>Company</th>
      <th>Address</th>
      <th>District</th>
      <th>Long</th>
      <th>Lat</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @channels.each do |channel| %>
      <tr>
        <td><%= channel.company %></td>
        <td><%= channel.address %></td>
        <td><%= channel.district.name %></td>
        <td><%= channel.long %></td>
        <td><%= channel.lat %></td>
        <td><%= channel.status %></td>
        <td><%= link_to 'Show', channel %></td>
        <td><%= link_to 'Edit', edit_channel_path(channel) %></td>
        <td><%= link_to 'Destroy', channel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Channel', new_channel_path %><br>
<%= link_to 'Back', welcome_index_path %>

app/views/channels/new.html.erb
<h1>New Channel</h1>

<%= render 'form', channel: @channel %>

<%= link_to 'Back', channels_path %>

app/views/channels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company:</strong>
  <%= @channel.company %>
</p>

<p>
  <strong>Address:</strong>
  <%= @channel.address %>
</p>

<p>
  <strong>District:</strong>
  <%= @channel.district.name %>
</p>

<p>
  <strong>Long:</strong>
  <%= @channel.long %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @channel.lat %>
</p>

<p>
  <strong>Status:</strong>
  <%= @channel.status %>
</p>

<%= link_to 'Edit', edit_channel_path(@channel) %> |
<%= link_to 'Back', channels_path %>