config/routes.rb
Rails.application.routes.draw do
  # get 'welcome/index', to: 'welcome#index'

  resources :channels
  resources :districts
  resources :cities
  resources :provinces
  resources :welcome

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @provinces = Province.all
    @cities = City.all
    @districts = District.all
    @channels = Channel.all
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<div class="container text-center">    
    <h1>Welcome</h1><br><br>

    <%= link_to 'Channel', channels_path %><br><br>
    <%= link_to 'District', districts_path %><br><br>
    <%= link_to 'City', cities_path %><br><br>
    <%= link_to 'Province', provinces_path %><br><br>
</div>

<div class="container">
  <div class="upper">
    <div class="row">
        <div class="col">
          <h1>Province</h1>
          <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deserunt rerum iste id adipisci sunt voluptas optio sequi, asperiores eaque ut eos eius mollitia totam velit voluptates maiores laudantium a ad.</p>
        </div>
        <div class="col">
            <table class="table">
              <thead>
                <tr>
                    <th>Name</th>
                </tr>
              </thead>
              <tbody>
                <% @provinces.each do |province| %>
                <tr>
                  <td>
                      <%= province.name %>
                  </td>
                </tr>
                <% end %>
              </tbody>
            </table>
        </div>
    </div>
  </div>

  <div class="upper">
    <div class="row">
      <div class="col">
        <h1>City</h1>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deserunt rerum iste id adipisci sunt voluptas optio sequi, asperiores eaque ut eos eius mollitia totam velit voluptates maiores laudantium a ad.</p>
      </div>
      <div class="col">
        <table class="table">
          <thead>
          <tr>
              <th>Name</th>
              <th class="col">Province</th>
          </tr>
          </thead>
          <tbody>
          <% @cities.each do |city| %>
          <tr>
              <td><%= city.name %></td>
              <td><%= city.province.name %></td>
          </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

  <div class="upper">
    <div class="row">
      <div class="col">
        <h1>District</h1>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deserunt rerum iste id adipisci sunt voluptas optio sequi, asperiores eaque ut eos eius mollitia totam velit voluptates maiores laudantium a ad.</p>
      </div>
      <div class="col">
        <table class="table">
            <thead>
            <tr>
                <th>Name</th>
                <th class="col">City</th>
            </tr>
            </thead>
            <tbody>
            <% @districts.each do |district| %>
            <tr>
                <td><%= district.name %></td>
                <td><%= district.city.name %></td>
            </tr>
            <% end %>
            </tbody>
        </table>
    </div>
  </div>

  <div class="upper">
    <div class="row">
      <div class="col">
        <h1>Channel</h1>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deserunt rerum iste id adipisci sunt voluptas optio sequi, asperiores eaque ut eos eius mollitia totam velit voluptates maiores laudantium a ad.</p>
      </div>
      <div class="col">
        <table class="table">
          <thead>
            <tr>
              <th>Company</th>
              <th>Address</th>
              <th>District</th>
              <th>Long</th>
              <th>Lat</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            <% @channels.each do |channel| %>
            <tr>
              <td><%= channel.company %></td>
              <td><%= channel.address %></td>
              <td> <%= channel.district.name %></td>
              <td><%= channel.long %></td>
              <td><%= channel.lat %></td>
              <td><%= channel.status %></td>
            </tr
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>