config/routes.rb
Rails.application.routes.draw do
  # get 'welcome/index', to: 'welcome#index'

  resources :channels
  resources :districts
  resources :cities
  resources :provinces
  resources :welcome

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/province.rb
class Province < ApplicationRecord
end

app/controllers/provinces_controller.rb
class ProvincesController < ApplicationController
  before_action :set_province, only: [:show, :edit, :update, :destroy]

  # GET /provinces
  # GET /provinces.json
  def index
    @provinces = Province.all
    data_json = []
    @provinces.each do |province|
      data_json << {name: province.name}
    end
    @data_json = data_json.to_json
  end

  # GET /provinces/1
  # GET /provinces/1.json
  def show
  end

  # GET /provinces/new
  def new
    @province = Province.new
  end

  # GET /provinces/1/edit
  def edit
  end

  # POST /provinces
  # POST /provinces.json
  def create
    @province = Province.new(province_params)

    respond_to do |format|
      if @province.save
        format.html { redirect_to @province, notice: 'Province was successfully created.' }
        format.json { render :show, status: :created, location: @province }
      else
        format.html { render :new }
        format.json { render json: @province.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /provinces/1
  # PATCH/PUT /provinces/1.json
  def update
    respond_to do |format|
      if @province.update(province_params)
        format.html { redirect_to @province, notice: 'Province was successfully updated.' }
        format.json { render :show, status: :ok, location: @province }
      else
        format.html { render :edit }
        format.json { render json: @province.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /provinces/1
  # DELETE /provinces/1.json
  def destroy
    @province.destroy
    respond_to do |format|
      format.html { redirect_to provinces_url, notice: 'Province was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_province
      @province = Province.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def province_params
      params.require(:province).permit(:name)
    end
end

app/helpers/provinces_helper.rb
module ProvincesHelper
end

app/views/provinces/_form.html.erb
<%= form_with(model: province, local: true) do |form| %>
  <% if province.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(province.errors.count, "error") %> prohibited this province from being saved:</h2>

      <ul>
      <% province.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :province_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/provinces/edit.html.erb
<h1>Editing Province</h1>

<%= render 'form', province: @province %>

<%= link_to 'Show', @province %> |
<%= link_to 'Back', provinces_path %>

app/views/provinces/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Provinces</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @provinces.each do |province| %>
      <tr>
        <td><%= province.name %></td>
        <td><%= link_to 'Show', province %></td>
        <td><%= link_to 'Edit', edit_province_path(province) %></td>
        <td><%= link_to 'Destroy', province, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Province', new_province_path %><br>
<%= link_to 'Back', welcome_index_path %>

app/views/provinces/new.html.erb
<h1>New Province</h1>

<%= render 'form', province: @province %>

<%= link_to 'Back', provinces_path %>

app/views/provinces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @province.name %>
</p>

<%= link_to 'Edit', edit_province_path(@province) %> |
<%= link_to 'Back', provinces_path %>